name: CI for Angular
on: push
jobs:
  services-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Exceute tests
        run: npm run test -- --no-watch --code-coverage --browsers=ChromeHeadlessCI
